services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'


#services:
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: my_docker_db
#    ports:
#      - "3306:3306" # Expose port 3306
#    networks:
#      - my_network
#
#networks:
#  my_network:
#    driver: bridge

#
#
#    spring.datasource.url=jdbc:mysql://db:3306/my_docker_db