create SCHEMA IF NOT EXISTS pgdemo;
create TABLE IF NOT EXISTS pgdemo.users2 (
	id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    phone_number VARCHAR(15),
    address VARCHAR(50),
    date_of_birth DATE,
    is_active BOOLEAN DEFAULT TRUE);